version: '3.8'
volumes:
  downloads:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_MEDIA_FOLDER}downloads"
  tv:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_MEDIA_FOLDER}tv"
  movies:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_MEDIA_FOLDER}movies"
  transmission_config:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_CONFIG_FOLDER}transmission"
  jellyfin_config:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_CONFIG_FOLDER}jellyfin"
  jellyseerr_config:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_CONFIG_FOLDER}jellyseerr"
  radarr_config:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_CONFIG_FOLDER}radarr"
  sonarr_config:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_CONFIG_FOLDER}sonarr"
  bazarr_config:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_CONFIG_FOLDER}bazarr"
  prowlarr_config:
    driver_opts:
      type: "nfs"
      o: ${NFS_IP_OPTIONS}
      device: "${NFS_CONFIG_FOLDER}prowlarr"
services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - downloads:/data
      - transmission_config:/config
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=UK London
      - OPENVPN_USERNAME=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASS}
      - LOCAL_NETWORK=192.168.1.0/24
      - NORDVPN_COUNTRY=GB
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - jellyfin_config:/config
      - tv:/tv
      - movies:/movies
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    #environment:
    #  - JELLYFIN_PublishedServerUrl=http://rasbpi.local
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Etc/UTC
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_config:/app/config
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:arm32v7-4.5.2
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr_config:/config
      - movies:/movies
      - downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:arm32v7-3.0.9
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr_config:/config
      - tv:/tv
      - downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr:arm32v7-1.2.1
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - bazarr_config:/config
      - tv:/tv
      - movies:/movies
      - downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

  # INDEXING
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
