# 8080 = qBittorrent (Proxy via Gluetun)
# 8096 = Jellyfin
# 9696 = Prowlerr
# 8989 = Sonarr
# 6767 = Bazarr
# 5055 = Overseerr
# 8787 = Readarr
# 9081 = Calibre
# 7575 = Homarr

version: "3"
services:

  # DOWNLOADING
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qBittorrent web ui
    volumes:
      - ${CONFIG_LOC}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASS}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - TZ=UTC
  qbittorrent:
    network_mode: "service:gluetun" # Use Gluetun network (nordvpn)
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_LOC}/qbittorrent:/config
      - ${DOWNLOADS_LOC}:/downloads
    # Commented due to Gluetun proxying ports.
    #ports:
      #- 8080:8080
      #- 6881:6881
      #- 6881:6881/udp
    restart: unless-stopped


  # INDEXING
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  

  # TV AND MOVIES
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CONFIG_LOC}/jellyfin:/config
      - ${TV_LOC}:/data/tvshows
      - ${MOVIES_LOC}:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/sonarr:/config
      - ${TV_LOC}:/tv
      - ${DOWNLOADS_LOC}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/bazarr:/config
      - ${TV_LOC}:/tv
      - ${MOVIES_LOC}:/movies
      - ${DOWNLOADS_LOC}:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/radarr:/config
      - ${MOVIES_LOC}:/movies
      - ${DOWNLOADS_LOC}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Etc/UTC
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_LOC}/jellyseerr:/app/config
    restart: unless-stopped
  

  # READING
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG_LOC}/readarr:/config
      - ${BOOKS_LOC}:/books
      - ${DOWNLOADS_LOC}:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${CONFIG_LOC}/calibre-web:/config
      - ${BOOKS_LOC}:/books
    ports:
      - 8083:8083
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/calibre:/config
    ports:
      - 9080:8080
      - 9181:8181
      - 9081:8081
    restart: unless-stopped

  # PROXY
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG_LOC}/homarr:/app/data/configs
      - ${ICONS_LOC}:/app/public/icons
    ports:
      - 7575:7575
