version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
    volumes:
      - ${CONFIG_LOC}/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=nordvpn
      # OpenVPN:
      - OPENVPN_USER=Ap8rwzp68CME7rsZpydj9rWL
      - OPENVPN_PASSWORD=JAmmvn6JQ911XMSAGfVkWKyS
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=UTC
      # Server list updater. See https://github.com/qdm12/gluetun/wiki/Updating-Servers#periodic-update
      - UPDATER_PERIOD=
      - UPDATER_VPN_SERVICE_PROVIDERS=
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CONFIG_LOC}/jellyfin:/config
      - ${TV_LOC}:/data/tvshows
      - ${MOVIES_LOC}:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/sonarr:/config
      - ${TV_LOC}:/tv
      - ${DOWNLOADS_LOC}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  qbittorrent:
    network_mode: "service:gluetun"
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_LOC}/qbittorrent:/config
      - ${DOWNLOADS_LOC}:/downloads
    #ports:
      #- 8080:8080
      #- 6881:6881
      #- 6881:6881/udp
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/bazarr:/config
      - ${TV_LOC}:/tv
      - ${MOVIES_LOC}:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_LOC}/radarr:/config
      - ${MOVIES_LOC}:/movies #optional
      - ${DOWNLOADS_LOC}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped